### ISSUE TITLE
Wrong handling of strings.

### ISSUE THREAD

**Issue by cryptoboy** [ellisonch/warpwallet#2]
I have submitted a pull request that fixes said issues, but it seems it has fallen off the radar.

If you disagree with the proposed change, I'd like to know why.

**Comment by ellisonch** [comment]
I redid the way I was processing input, so now testcases can be written.

I wound up using the scanner because it seems like the idiomatic way to do it, and I wanted to keep trailing spaces (since the reference implementation allows them).

I also threw up a warning in case the inputs end in an \r.

If there are any more problems, hopefully a failing test case can be written first.

Thanks for your contribution :)
